### ISSUE TITLE
Hangs with rdonly: true

### ISSUE THREAD

**Issue by paddor** [minad/lmdb#50]
I'm experiencing hangs (with `LMDB.new 'path/database/', rdonly: true`) and believe that an update of the LMDB sources could fix these issues.

**Comment by paddor** [comment]
Any updates?

**Comment by doriantaylor** [comment]
From what I can tell the design of the transaction handling in the binding never really supported read-only transactions, and needs to be completely overhauled. [See this thread](https://lists.openldap.org/hyperkitty/list/openldap-technical@openldap.org/thread/I4EKSYY6ID47ZJCNXGJKBBPWVJW7UUBS/?sort=date).

**Comment by paddor** [comment]
@doriantaylor Thanks
