### ISSUE TITLE
Adding support for jumping straight to key-value pairs (`MDB_GET_BOTH`)

### ISSUE THREAD

**Issue by doriantaylor** [minad/lmdb#51]
I've written a patch to expose cursor calls to `MDB_GET_BOTH` by way of an additional argument to `cursor.set key, value`. On a database with `:dupsort` set, it will jump the cursor to the key-value pair or return nil. This way one doesn't have to iterate over the entire cursor to test if a given pair is present.

To that effect, I also added a `database.has? key, value` which will test if a key (optionally key-value pair) exists in the database, whether or not `:dupsort` is set. This also required writing a `database.flags` method to pull the flags out.

Work is going [over here](https://github.com/doriantaylor/lmdb/tree/cursor-get-both); I'll let you respond before I PR.

**Comment by minad** [comment]
The project is essentially unmaintained

**Comment by casperisfine** [comment]
> The project is essentially unmaintained

What's the status on this? I see #53 was merged by @doriantaylor, does that mean the project is maintained again?

This gem is very useful to us, and it need some updating for Ruby 2.7+ compatibility. I'm willing to put the time to submit PRs, but if there's no longer a maintainer I might as well build a new gem.

**Comment by doriantaylor** [comment]
I have [already solved for the deprecation warnings in 2.7](https://github.com/doriantaylor/lmdb/tree/reconcile-2.7) but not released yet because there are some memory issues around transactions in concurrent environments. I was waiting for some input from the OpenLDAP people before proceeding to fix them and only just recently got the information I needed.

I can clean that up and release something this week.

**Comment by casperisfine** [comment]
That's great news. I'll close my open PR then.

Thanks!

**Comment by doriantaylor** [comment]
Just pushed 0.5.3.

**Comment by casperisfine** [comment]
Wow, thanks a lot!

**Comment by doriantaylor** [comment]
There are certain questions which are still indeterminate like which repo to use going forward, and some tidy way of keeping the embedded lmdb source up to date that does not involve keeping it in version control which I can't really address right now, but happy hunting!

**Comment by casperisfine** [comment]
> some tidy way of keeping the embedded lmdb source up to date that does not involve keeping it in version control

Is it that big of a deal? I'm not really for vendoring in general, but for C libraries it's usually fine, and makes using the gem from a git branch a breeze.

**Comment by doriantaylor** [comment]
oh i was just gonna do something that downloads the latest lmdb when the gem is built; i just have to research the best way to go about that.

**Comment by casperisfine** [comment]
I'd advise against this kind of stuff. It's a recipe for the gem starting to break out of nowhere when upstream changes something.

While it's a bit more work for the maintainer, it's much better for users if each gem version stick to a particular lmdb version, and if the lmdb sources are packaged inside the gem.

**Comment by casperisfine** [comment]
A better compromise IMHO would be to have a script inside the repo to update the lmdb source.

**Comment by doriantaylor** [comment]
i mean when the gem is packaged by the maintainer (me apparently), not when it is installed by the user

**Comment by casperisfine** [comment]
Oh! 

Well then you can implement it as a rake task, and make it a dependency of the existing `compile` task.

**Comment by doriantaylor** [comment]
yeah i'll figure it out; just have a client project to finish first. thanks!

**Comment by casperisfine** [comment]
Sorry to bother once again, but I can't find the 0.5.3 commit pushed on either `minad/lmdb` or `doriantaylor/lmdb`. It makes verifying the diff harder :/

**Comment by doriantaylor** [comment]
https://github.com/doriantaylor/lmdb/tree/v0.5.3
