### ISSUE TITLE
looking for new maintainer

### ISSUE THREAD

**Issue by minad** [minad/lmdb#52]
Ping @vjoel @doriantaylor @tamuratak @ms-ati

**Comment by doriantaylor** [comment]
Sure; I'm just not familiar with the handoff process on rubygems.

**Comment by vjoel** [comment]
I fully support finding a new maintainer--I've been absent on this for years!

Handoff on rubygems is easy, IIRC. The new maintainer has to have a rubygems account, and then the owner just adds them.

**Comment by doriantaylor** [comment]
Welp I just [implemented a quad store](/doriantaylor/rb-rdf-lmdb) on top of it…

**Comment by minad** [comment]
@doriantaylor For now, I added you as collaborator to the repository.

**Comment by doriantaylor** [comment]
Thanks!

**Comment by doriantaylor** [comment]
How do you feel about upping the required Ruby version to the same as Moneta to clear off that complaint from Travis?

**Comment by minad** [comment]
Yes that's good. Feel free to make any change that moves things forward. I've been out of the loop of ruby development for a while.

**Comment by doriantaylor** [comment]
@vjoel I see you patched #23 about 5 years ago to bring 1.9.3 support back. Do you know if it's safe to blow away, or otherwise how to get either the Travis build to pass on 1.9.3?

**Comment by minad** [comment]
@doriantaylor I think it makes safe to only support recent ruby versions, which are not eol?

**Comment by vjoel** [comment]
Yes, 1.9.3 is eol: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by doriantaylor** [comment]
Cool, just wanted to make sure that since you made an explicit point of bringing it back in that patch, that you didn't have some legacy thing running somewhere before I go changing anything.

**Comment by doriantaylor** [comment]
Pushed my changes to master and bumped to 0.5.1; removed eol rubies that were complaining.
